// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pofidqkzmqxbskazxmnu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBvZmlkcWt6bXF4YnNrYXp4bW51Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2NTQxNzYsImV4cCI6MjA2NDIzMDE3Nn0.EMNQs_YRQN6CpXQBzZh3fLWaPRrhm7paRgVV_4MrxQQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);