// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iagkylxqlartqokuiahf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlhZ2t5bHhxbGFydHFva3VpYWhmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyMDcxNzcsImV4cCI6MjA2Nzc4MzE3N30.v6oJVKBCkjx3uhuDpws1lM-h4Xu0FzmeUZVDyG3P5sY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    storageKey: 'can2curb-auth-token'
  }
});

// Legacy exports for compatibility
export type UserRole = 'customer' | 'employee' | 'admin';

/**
 * SECURITY: Role is no longer stored in profiles table
 * Use permissionManager to check roles via user_roles table
 */
export interface UserData {
  id: string;
  email?: string;
  role?: UserRole; // DEPRECATED: Use user_roles table instead
  full_name?: string;
  phone?: string;
  address?: string;
  drivers_license?: string;
  job_title?: string;
  pay_rate?: number;
  status?: string;
  created_at?: string;
  updated_at?: string;
}